@startuml
participant User
participant App
entity KeyPair
participant BackEnd
participant FireBase
participant Nuts
participant OZO


group Setup OZO
User -> App: start with OZO
App <--> User: something biometric
App -> KeyPair: create
App -> KeyPair: sign JWT
App -> App: create data (Request + METHOD + jti (uuid))
KeyPair --> App: signed data + public key
App -> BackEnd: init OZO (signed data + public key)
BackEnd -> BackEnd: verify signature signed data
BackEnd -> FireBase: register hash(public key)
BackEnd -> Nuts: create subject subject=firebase identity
BackEnd -> OZO: fetch credentials
OZO -> Nuts: place credential
OZO <--> User: log in
OZO --> BackEnd: done
end

group Use OZO
User -> App: view OZO messages OZO
App <--> User: something biometric
App -> KeyPair: unseal
App -> App: create data (Request + METHOD + jti (uuid))
App -> KeyPair: sign JWT
KeyPair --> App: signed data + public key
App -> BackEnd: fetch data (sign JWT + public key)
BackEnd -> BackEnd: verify signature signed data
BackEnd -> FireBase: validate hash(public key) met firebase attrubuut
BackEnd -> OZO: get accesstoken subject=firebase identity

end


group Encryption
App -> BackEnd: give public key
BackEnd -> BackEnd: generate data to encrypt
BackEnd -> BackEnd: encryption data w/public key
BackEnd --> App: encrypted data
App -> KeyPair: decrypt data
App -> BackEnd: GET + decrypted data

end




@enduml
