
@startuml
actor user
control "Client application" as client_app
control "NUTS node client" as client_nuts
boundary "OZO issuer" as ozo_issuer

group Issue User Access VC

user -> client_app
client_app -> client_nuts: request VC issuance
client_nuts -> ozo_issuer: request VC
ozo_issuer -> user: authenticate
user --> ozo_issuer: user credentials
ozo_issuer -> ozo_issuer: create VC
ozo_issuer --> client_nuts: issue VC
client_nuts -> client_nuts: store VC
client_nuts --> client_app: done

end
@enduml
