@startuml

actor user
control client_administrator
control x509_toolkit
control client_nuts
control client_app

boundary ozo_administrator
control ozo_nuts


group Self sign X509Credential
client_administrator -> client_nuts: create subject
client_nuts --> client_administrator: did:web
client_administrator -> x509_toolkit: issue VC (UZI cert, private key, did:web)
x509_toolkit --> client_administrator: X509Credential
client_administrator -> client_nuts: store X509Credential
end

group Request NutsOrganizationCredential
client_administrator -> ozo_administrator: request NutsOrganizationCredential issuance with URA nr
ozo_administrator -> client_nuts: create NutsOrganizationCredential
client_nuts --> ozo_administrator: NutsOrganizationCredential
ozo_administrator --> client_administrator: NutsOrganizationCredential
client_administrator -> client_nuts: store NutsOrganizationCredential
end

@enduml
