pages:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker pull $CI_REGISTRY/headease/ozo-refererence-impl/headease-ig-builder/main:latest
    - mkdir ./public
    - docker run --rm -v "${PWD}/input:/app/input" -v "${PWD}/public:/app/output" $CI_REGISTRY/headease/ozo-refererence-impl/headease-ig-builder/main:latest
  artifacts:
    paths:
    - public
  only:
  - main
