pages:
  image: docker:latest
  stage: build
  services:
    - docker:stable-dind
  variables:
    IMAGE_NAME: $CI_REGISTRY/headease/ozo-refererence-impl/headease-ig-builder/main:latest
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker pull $IMAGE_NAME
    - mkdir ./public
    - docker run --rm  -v "${PWD}/input:/workspace/input" -v "${PWD}/public:/workspace/output" --mount type=bind,source=${PWD}/ig.ini,target=/workspace/ig.ini --mount type=bind,source=${PWD}/sushi-config.yaml,target=/workspace/sushi-config.yaml $IMAGE_NAME
  artifacts:
    paths:
    - public
  only:
  - main
