pages:
  image: docker
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker pull $CI_REGISTRY/headease/ozo-refererence-impl/headease-ig-builder/main:latest
    - docker run -v .:/workspace $CI_REGISTRY/headease/ozo-refererence-impl/headease-ig-builder/main
  artifacts:
    paths:
    - output
  only:
  - main
