pages:
  image: $CI_REGISTRY/headease/ozo-refererence-impl/headease-ig-builder/main:latest
  stage: build
  script:
    - /workspace/_updatePublisher.sh
    - bash _genonce.sh
  artifacts:
    paths:
    - output
  only:
  - main
