pages:
  image: docker:24.0.5
  stage: build
  services:
    - docker:24.0.5-dind
  variables:
    IMAGE_NAME: $CI_REGISTRY/headease/ozo-refererence-impl/headease-ig-builder/main:latest
    DOCKER_HOST: "tcp://docker:2375"
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker pull $IMAGE_NAME
    - mkdir ./public
    - docker run --rm  -v "${PWD}/input:/workspace/input" -v "${PWD}/public:/workspace/output" -v "${PWD}/ig.ini:/workspace/ig.ini" -v "${PWD}/sushi-config.yaml:/workspace/sushi-config.yaml" $IMAGE_NAME
  artifacts:
    paths:
    - public
  only:
  - main
